// JsFromRoutes CacheKey 0a478a5c1b9019b94042d1708355bd1c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/expenses'),
  create: definePathHelper('post', '/expenses'),
  new: definePathHelper('get', '/expenses/new'),
  edit: definePathHelper('get', '/expenses/:id/edit'),
  get: definePathHelper('get', '/expenses/:id'),
  update: definePathHelper('patch', '/expenses/:id'),
  destroy: definePathHelper('delete', '/expenses/:id'),
}
