// JsFromRoutes CacheKey 9fe649814641129d32bb368835bdf345
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/login'),
  create: definePathHelper('post', '/login'),
  destroy: definePathHelper('delete', '/logout'),
}
